### ISSUE TITLE
Failed to activate the navigation-history package

### ISSUE THREAD

**Issue by cbrunnkvist** [Tyriar/navigation-history#14]
This error pops up each time I start Atom since I installed this package.

**Atom Version**: 1.12.9
**Electron Version**: 1.3.13
**System**: Mac OS X 10.12.2
**Thrown From**: [navigation-history](https://github.com/Tyriar/navigation-history) package, v0.1.8

### Stack Trace

Failed to activate the navigation-history package

```
At editor is not defined

ReferenceError: editor is not defined
    at new CursorWatcher (/Users/conny/.atom/packages/navigation-history/lib/cursor-watcher.coffee:4:5)
    at /Users/conny/.atom/packages/navigation-history/lib/main.coffee:22:27
    at Workspace.module.exports.Workspace.observeTextEditors (/Users/conny/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:329:9)
    at Object.activate (/Users/conny/.atom/packages/navigation-history/lib/main.coffee:21:20)
    at Package.module.exports.Package.activateNow (/Users/conny/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:184:19)
    at /Users/conny/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:157:32
    at Package.module.exports.Package.measure (/Users/conny/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Users/conny/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:150:26
[... shortened ...]

**Comment by cbrunnkvist** [comment]
Oh I see - it's unmaintained. Also, ticket duplicate of #13
