### ISSUE TITLE
Failed to activate the navigation-history package

### ISSUE THREAD

**Issue by rodrigopoi** [Tyriar/navigation-history#15]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0-beta2 x64
**Electron**: 1.3.13
**OS**: Unknown Windows version
**Thrown From**: [navigation-history](https://github.com/Tyriar/navigation-history) package 0.1.8

### Stack Trace

Failed to activate the navigation-history package

```
At editor is not defined

ReferenceError: editor is not defined
    at /packages/navigation-history/lib/cursor-watcher.coffee:4:5)
    at /packages/navigation-history/lib/main.coffee:22:27
    at Workspace.module.exports.Workspace.observeTextEditors (/app.asar/src/workspace.js:329:9)
    at Object.activate (/packages/navigation-history/lib/main.coffee:21:20)
    at Package.module.exports.Package.activateNow (/app.asar/src/package.js:218:19)
    at /app.asar/src/package.js:190:32
    at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
    at /app.asar/src/package.js:183:26
    at Package.module.exports.Package.activate (/app.asar/src/package.js:180:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/app.asar/src/package-manager.js:550:34)
    at /app.asar/src/package-manager.js:352:19
    at /app.asar/src/config.js:635:20
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at Config.module.exports.Config.emitChangeEvent (/app.asar/src/config.js:826:29)
    at Config.module.exports.Config.setRawValue (/app.asar/src/config.js:612:19)
    at Config.module.exports.Config.set (/app.asar/src/config.js:227:14)
    at Config.module.exports.Config.removeAtKeyPath (/app.asar/src/config.js:377:12)
    at Package.module.exports.Package.enable (/app.asar/src/package.js:81:26)
    at PackageManager.module.exports.PackageManager.enablePackage (/app.asar/src/package-manager.js:173:14)
    at /app.asar/node_modules/settings-view/lib/package-card.js:348:27)
    at HTMLButtonElement.dispatch (/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLButtonElement.elemData.handle (/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
  7x -1:01.1.0 navigation-history:back (input.hidden-input)
     -0:28.6.0 core:paste (input.hidden-input)
     -0:25.2.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
angularjs 0.4.0 
atom-angular-material-snippets 1.3.0 
atom-beautify 0.29.17 
atom-ternjs 0.17.2 
autoclose-html 0.23.0 
chrome-color-picker 0.8.0 
editorconfig 2.2.1 
formatter 2.12.4 
lint 0.0.1 
linter 1.11.23 
linter-csslint 1.3.3 
linter-eslint 8.1.2 
linter-jscs 4.1.1 
linter-sass-lint 1.7.4 
navigation-history 0.1.8 
quick-highlight 0.8.1 
webbox-color 0.5.9 
```

**Comment by ivan-nejezchleb** [comment]
+1 for this issue
