### ISSUE TITLE
Failed to activate the navigation-history package

### ISSUE THREAD

**Issue by tinymins** [Tyriar/navigation-history#16]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: [navigation-history](https://github.com/Tyriar/navigation-history) package 0.1.8

### Stack Trace

Failed to activate the navigation-history package

```
At editor is not defined

ReferenceError: editor is not defined
    at /packages/navigation-history/lib/cursor-watcher.coffee:4:5)
    at /packages/navigation-history/lib/main.coffee:22:27
    at Workspace.module.exports.Workspace.observeTextEditors (/app.asar/src/workspace.js:329:9)
    at Object.activate (/packages/navigation-history/lib/main.coffee:21:20)
    at Package.module.exports.Package.activateNow (/app.asar/src/package.js:218:19)
    at /app.asar/src/package.js:190:32
    at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
    at /app.asar/src/package.js:183:26
    at Package.module.exports.Package.activate (/app.asar/src/package.js:180:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/app.asar/src/package-manager.js:550:34)
    at /app.asar/src/package-manager.js:352:19
    at /app.asar/src/config.js:635:20
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at Config.module.exports.Config.emitChangeEvent (/app.asar/src/config.js:826:29)
    at Config.module.exports.Config.setRawValue (/app.asar/src/config.js:612:19)
    at Config.module.exports.Config.set (/app.asar/src/config.js:227:14)
    at Config.module.exports.Config.removeAtKeyPath (/app.asar/src/config.js:377:12)
    at Package.module.exports.Package.enable (/app.asar/src/package.js:81:26)
    at PackageManager.module.exports.PackageManager.enablePackage (/app.asar/src/package-manager.js:173:14)
    at /app.asar/node_modules/settings-view/lib/package-card.js:348:27)
    at HTMLButtonElement.dispatch (/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLButtonElement.elemData.handle (/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
```

### Non-Core Packages

```
activate-power-mode 1.3.0 
atom-alignment 0.12.1 
define-jump 1.0.1 
file-header 1.13.2 
flatland-dark 0.2.2 
flatland-dark-ui 0.2.5 
git-plus 7.3.3 
highlight-selected 0.12.0 
language-batch 0.4.0 
language-lua 0.9.11 
minimap 4.26.8 
mukluk-syntax 0.4.0 
navigation-history 0.1.8 
script 3.14.1 
seti-syntax 1.1.2 
seti-ui 1.6.1 
```

**Comment by bobmoff** [comment]
+1

I get the same error

**Comment by treyerl** [comment]
+1
